# Auto-generated by ros2_systemd_manager
# Re-generate with: make update

SUDO ?= sudo
SCRIPT ?= ros2-systemd-manager
CONFIG ?=
WORKSPACE_KEY ?=
UNITS := ros2-foxglove-bridge.service ros2-soem-bringup.service ros2-infantry-chassis.service ros2-sp-vision-autoaim.service
GENERATED_MK := $(lastword $(MAKEFILE_LIST))

EFFECTIVE_SCRIPT := $(if $(strip $(SCRIPT)),$(SCRIPT),ros2-systemd-manager)
EFFECTIVE_CONFIG := $(if $(strip $(CONFIG)),$(CONFIG),$(firstword $(wildcard ./ros2_services.yaml ./*.yaml)))

.PHONY: help upgrade ensure-config install apply uninstall start stop restart status status-long enable disable logs logs-recent update makefile start-ros2-foxglove-bridge stop-ros2-foxglove-bridge restart-ros2-foxglove-bridge status-ros2-foxglove-bridge status-ros2-foxglove-bridge-long enable-ros2-foxglove-bridge disable-ros2-foxglove-bridge logs-ros2-foxglove-bridge logs-ros2-foxglove-bridge-recent start-ros2-soem-bringup stop-ros2-soem-bringup restart-ros2-soem-bringup status-ros2-soem-bringup status-ros2-soem-bringup-long enable-ros2-soem-bringup disable-ros2-soem-bringup logs-ros2-soem-bringup logs-ros2-soem-bringup-recent start-ros2-infantry-chassis stop-ros2-infantry-chassis restart-ros2-infantry-chassis status-ros2-infantry-chassis status-ros2-infantry-chassis-long enable-ros2-infantry-chassis disable-ros2-infantry-chassis logs-ros2-infantry-chassis logs-ros2-infantry-chassis-recent start-ros2-sp-vision-autoaim stop-ros2-sp-vision-autoaim restart-ros2-sp-vision-autoaim status-ros2-sp-vision-autoaim status-ros2-sp-vision-autoaim-long enable-ros2-sp-vision-autoaim disable-ros2-sp-vision-autoaim logs-ros2-sp-vision-autoaim logs-ros2-sp-vision-autoaim-recent

help:
	@echo "Targets:"
	@echo "  make upgrade                # self-upgrade ros2-systemd-manager via pip"
	@echo "  make install                # install unit files only"
	@echo "  make apply                  # install + start + enable"
	@echo "  make start                  # systemctl start all configured units"
	@echo "  make stop                   # systemctl stop all configured units"
	@echo "  make restart                # systemctl restart all configured units"
	@echo "  make status                 # systemctl status all configured units"
	@echo "  make status-long            # systemctl status with 100 log lines"
	@echo "  make enable                 # systemctl enable all configured units"
	@echo "  make disable                # systemctl disable all configured units"
	@echo "  make logs                   # follow logs for all configured units"
	@echo "  make <op>-<service>         # op in start/stop/restart/status/enable/disable/logs"
	@echo "  make <op>-<service>-<sfx>   # e.g. status-<svc>-long, logs-<svc>-recent"
	@echo "  make uninstall              # uninstall all configured units"
	@echo "  make update                 # stop old + uninstall removed + install/start/enable + refresh generated mk"
	@echo "  make makefile               # refresh generated mk only (no systemd changes)"
	@echo "  make <target> CONFIG=./file.yaml  # override auto-discovered yaml"

ensure-config:
	@if [ -z "$(EFFECTIVE_CONFIG)" ]; then \
		echo "ERROR: no yaml config found in current directory (expected ./ros2_services.yaml or ./*.yaml)."; \
		exit 1; \
	fi

upgrade:
	$(EFFECTIVE_SCRIPT) upgrade

install: ensure-config
	$(SUDO) $(EFFECTIVE_SCRIPT) install --config "$(EFFECTIVE_CONFIG)" --workspace-key "$(WORKSPACE_KEY)"

apply: ensure-config
	$(SUDO) $(EFFECTIVE_SCRIPT) apply --config "$(EFFECTIVE_CONFIG)" --workspace-key "$(WORKSPACE_KEY)"

uninstall: ensure-config
	$(SUDO) $(EFFECTIVE_SCRIPT) uninstall --config "$(EFFECTIVE_CONFIG)" --workspace-key "$(WORKSPACE_KEY)"

start:
	$(SUDO) systemctl start $(UNITS)

stop:
	$(SUDO) systemctl stop $(UNITS)

restart:
	$(SUDO) systemctl restart $(UNITS)

status:
	$(SUDO) systemctl status $(UNITS)

status-long:
	$(SUDO) systemctl status $(UNITS) --no-pager -l -n 100

enable:
	$(SUDO) systemctl enable $(UNITS)

disable:
	$(SUDO) systemctl disable $(UNITS)

logs:
	$(SUDO) journalctl $(foreach u,$(UNITS),-u $(u)) -f

logs-recent:
	$(SUDO) journalctl $(foreach u,$(UNITS),-u $(u)) -n 200 --no-pager

update: ensure-config
	$(SUDO) $(EFFECTIVE_SCRIPT) update --config "$(EFFECTIVE_CONFIG)" --workspace-key "$(WORKSPACE_KEY)" --previous-makefile "$(GENERATED_MK)"

makefile: ensure-config
	$(EFFECTIVE_SCRIPT) makefile --config "$(EFFECTIVE_CONFIG)" --workspace-key "$(WORKSPACE_KEY)"


start-ros2-foxglove-bridge:
	$(SUDO) systemctl start "ros2-foxglove-bridge.service"

stop-ros2-foxglove-bridge:
	$(SUDO) systemctl stop "ros2-foxglove-bridge.service"

restart-ros2-foxglove-bridge:
	$(SUDO) systemctl restart "ros2-foxglove-bridge.service"

status-ros2-foxglove-bridge:
	$(SUDO) systemctl status "ros2-foxglove-bridge.service"

status-ros2-foxglove-bridge-long:
	$(SUDO) systemctl status "ros2-foxglove-bridge.service" --no-pager -l -n 100

enable-ros2-foxglove-bridge:
	$(SUDO) systemctl enable "ros2-foxglove-bridge.service"

disable-ros2-foxglove-bridge:
	$(SUDO) systemctl disable "ros2-foxglove-bridge.service"

logs-ros2-foxglove-bridge:
	$(SUDO) journalctl -u "ros2-foxglove-bridge.service" -n 100 -f

logs-ros2-foxglove-bridge-recent:
	$(SUDO) journalctl -u "ros2-foxglove-bridge.service" -n 200 --no-pager


start-ros2-soem-bringup:
	$(SUDO) systemctl start "ros2-soem-bringup.service"

stop-ros2-soem-bringup:
	$(SUDO) systemctl stop "ros2-soem-bringup.service"

restart-ros2-soem-bringup:
	$(SUDO) systemctl restart "ros2-soem-bringup.service"

status-ros2-soem-bringup:
	$(SUDO) systemctl status "ros2-soem-bringup.service"

status-ros2-soem-bringup-long:
	$(SUDO) systemctl status "ros2-soem-bringup.service" --no-pager -l -n 100

enable-ros2-soem-bringup:
	$(SUDO) systemctl enable "ros2-soem-bringup.service"

disable-ros2-soem-bringup:
	$(SUDO) systemctl disable "ros2-soem-bringup.service"

logs-ros2-soem-bringup:
	$(SUDO) journalctl -u "ros2-soem-bringup.service" -n 100 -f

logs-ros2-soem-bringup-recent:
	$(SUDO) journalctl -u "ros2-soem-bringup.service" -n 200 --no-pager


start-ros2-infantry-chassis:
	$(SUDO) systemctl start "ros2-infantry-chassis.service"

stop-ros2-infantry-chassis:
	$(SUDO) systemctl stop "ros2-infantry-chassis.service"

restart-ros2-infantry-chassis:
	$(SUDO) systemctl restart "ros2-infantry-chassis.service"

status-ros2-infantry-chassis:
	$(SUDO) systemctl status "ros2-infantry-chassis.service"

status-ros2-infantry-chassis-long:
	$(SUDO) systemctl status "ros2-infantry-chassis.service" --no-pager -l -n 100

enable-ros2-infantry-chassis:
	$(SUDO) systemctl enable "ros2-infantry-chassis.service"

disable-ros2-infantry-chassis:
	$(SUDO) systemctl disable "ros2-infantry-chassis.service"

logs-ros2-infantry-chassis:
	$(SUDO) journalctl -u "ros2-infantry-chassis.service" -n 100 -f

logs-ros2-infantry-chassis-recent:
	$(SUDO) journalctl -u "ros2-infantry-chassis.service" -n 200 --no-pager


start-ros2-sp-vision-autoaim:
	$(SUDO) systemctl start "ros2-sp-vision-autoaim.service"

stop-ros2-sp-vision-autoaim:
	$(SUDO) systemctl stop "ros2-sp-vision-autoaim.service"

restart-ros2-sp-vision-autoaim:
	$(SUDO) systemctl restart "ros2-sp-vision-autoaim.service"

status-ros2-sp-vision-autoaim:
	$(SUDO) systemctl status "ros2-sp-vision-autoaim.service"

status-ros2-sp-vision-autoaim-long:
	$(SUDO) systemctl status "ros2-sp-vision-autoaim.service" --no-pager -l -n 100

enable-ros2-sp-vision-autoaim:
	$(SUDO) systemctl enable "ros2-sp-vision-autoaim.service"

disable-ros2-sp-vision-autoaim:
	$(SUDO) systemctl disable "ros2-sp-vision-autoaim.service"

logs-ros2-sp-vision-autoaim:
	$(SUDO) journalctl -u "ros2-sp-vision-autoaim.service" -n 100 -f

logs-ros2-sp-vision-autoaim-recent:
	$(SUDO) journalctl -u "ros2-sp-vision-autoaim.service" -n 200 --no-pager
