import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from .config import resolve_makefile_path
from .runtime import err, log

AUTO_GENERATED_HEADER = "# Auto-generated by ros2_systemd_manager"
AUTO_INCLUDE_COMMENT = "# Auto-added by ros2_systemd_manager"


def _pick_main_makefile_path(base_dir: Path) -> Path:
    makefile_path = base_dir / "Makefile"
    lowercase_path = base_dir / "makefile"
    if makefile_path.exists():
        return makefile_path
    if lowercase_path.exists():
        return lowercase_path
    return makefile_path


def _ensure_main_makefile_includes_fragment(base_dir: Path, fragment_name: str) -> None:
    main_makefile = _pick_main_makefile_path(base_dir)
    include_line = f"include {fragment_name}"

    if main_makefile.exists():
        original_text = main_makefile.read_text(encoding="utf-8")
    else:
        original_text = ""

    # If old generated body is still present in main Makefile, strip it.
    cleaned_text = original_text
    lines = cleaned_text.splitlines()
    for idx, line in enumerate(lines):
        if line.strip() == AUTO_GENERATED_HEADER:
            prelude = lines[:idx]
            if all(
                (not item.strip())
                or item.strip().startswith("include ")
                or item.strip().startswith(AUTO_INCLUDE_COMMENT)
                for item in prelude
            ):
                cleaned_text = "\n".join(prelude)
            break

    include_re = re.compile(
        rf"^\s*-?include\s+{re.escape(fragment_name)}\s*$",
        flags=re.MULTILINE,
    )
    if include_re.search(cleaned_text):
        if cleaned_text != original_text:
            if cleaned_text and not cleaned_text.endswith("\n"):
                cleaned_text += "\n"
            main_makefile.write_text(cleaned_text, encoding="utf-8")
            log(
                f"Cleaned legacy generated body from main Makefile: {main_makefile}")
        return

    header_lines = [include_line,
                    f"{AUTO_INCLUDE_COMMENT}: include generated targets", ""]
    new_text = "\n".join(header_lines) + cleaned_text
    main_makefile.write_text(new_text, encoding="utf-8")
    log(f"Updated main Makefile include: {main_makefile}")


def _migrate_legacy_auto_generated_makefile(base_dir: Path, target_fragment_path: Path) -> None:
    if target_fragment_path.exists():
        return

    main_makefile = _pick_main_makefile_path(base_dir)
    if not main_makefile.exists():
        return

    makefile_text = main_makefile.read_text(encoding="utf-8")
    first_line = makefile_text.splitlines()[0].strip(
    ) if makefile_text.splitlines() else ""
    if first_line != AUTO_GENERATED_HEADER:
        return

    target_fragment_path.parent.mkdir(parents=True, exist_ok=True)
    target_fragment_path.write_text(makefile_text, encoding="utf-8")
    log(f"Migrated legacy auto-generated Makefile to: {target_fragment_path}")

    # Remove old generated content from main Makefile; it will be re-linked via include.
    main_makefile.write_text("", encoding="utf-8")


def build_makefile_content(
    *,
    script_default: str,
    unit_names: List[str],
    start_units: Optional[List[str]] = None,
    stop_units: Optional[List[str]] = None,
    restart_units: Optional[List[str]] = None,
) -> str:
    """Build Makefile content for service lifecycle operations."""
    # Default the guard-aware sets to "all units" so callers/tests that only pass
    # unit_names get the legacy behavior (every unit in every set).
    start_units = list(start_units) if start_units is not None else list(unit_names)
    stop_units = list(stop_units) if stop_units is not None else list(unit_names)
    restart_units = list(restart_units) if restart_units is not None else list(unit_names)
    quoted_units = " ".join(unit_names)
    quoted_start = " ".join(start_units)
    quoted_stop = " ".join(stop_units)
    quoted_restart = " ".join(restart_units)

    service_entries: List[Tuple[str, str]] = []
    seen_service_keys = set()
    for unit_name in unit_names:
        service_key = unit_name[:-
                                8] if unit_name.endswith(".service") else unit_name
        if service_key in seen_service_keys:
            continue
        seen_service_keys.add(service_key)
        service_entries.append((service_key, unit_name))

    per_service_targets: List[str] = []
    per_service_blocks: List[str] = []

    for service_key, unit_name in service_entries:
        per_service_targets.extend(
            [
                f"start-{service_key}",
                f"stop-{service_key}",
                f"restart-{service_key}",
                f"status-{service_key}",
                f"status-{service_key}-long",
                f"enable-{service_key}",
                f"disable-{service_key}",
                f"logs-{service_key}",
                f"logs-{service_key}-recent",
            ]
        )

        per_service_blocks.append(
            f"""
start-{service_key}:
\t$(SUDO) systemctl start \"{unit_name}\"

stop-{service_key}:
\t$(SUDO) systemctl stop \"{unit_name}\"

restart-{service_key}:
\t$(SUDO) systemctl restart \"{unit_name}\"

status-{service_key}:
\t$(SUDO) systemctl status \"{unit_name}\"

status-{service_key}-long:
\t$(SUDO) systemctl status \"{unit_name}\" --no-pager -l -n 100

enable-{service_key}:
\t$(SUDO) systemctl enable \"{unit_name}\"

disable-{service_key}:
\t$(SUDO) systemctl disable \"{unit_name}\"

logs-{service_key}:
\t$(SUDO) journalctl -u \"{unit_name}\" -n 100 -f

logs-{service_key}-recent:
\t$(SUDO) journalctl -u \"{unit_name}\" -n 200 --no-pager
""".rstrip()
        )

    phony_targets = " ".join(
        [
            "help",
            "upgrade",
            "ensure-config",
            "install",
            "apply",
            "uninstall",
            "start",
            "stop",
            "restart",
            "status",
            "status-long",
            "enable",
            "disable",
            "logs",
            "logs-recent",
            "update",
            "makefile",
            "list",
            "start-global",
            "stop-global",
            "restart-global",
            "status-global",
            "status-global-long",
            "enable-global",
            "disable-global",
            "logs-global",
            "logs-recent-global",
            "install-global",
            "apply-global",
            "uninstall-global",
            "update-global",
            "list-global",
            *per_service_targets,
        ]
    )

    per_service_blocks_text = "\n\n".join(per_service_blocks)

    return f"""# Auto-generated by ros2_systemd_manager
# Re-generate with: make update

SUDO ?= sudo
SCRIPT ?= {script_default}
CONFIG ?=
WORKSPACE_KEY ?=
UNITS := {quoted_units}
# Guard-aware subsets (explicit_start / explicit_stop excluded unless ALL=1).
START_UNITS := {quoted_start}
STOP_UNITS := {quoted_stop}
RESTART_UNITS := {quoted_restart}
GENERATED_MK := $(lastword $(MAKEFILE_LIST))

EFFECTIVE_SCRIPT := $(if $(strip $(SCRIPT)),$(SCRIPT),{script_default})
EFFECTIVE_CONFIG := $(if $(strip $(CONFIG)),$(CONFIG),$(firstword $(wildcard ./ros2_services.yaml ./*.yaml)))

# Every unit ever installed across all configs. Lazily expanded (the shell call
# runs only when a *-global target references it). ALL=1, GLOBAL=1, FORCE=1 are
# set on the command line, e.g. `make start ALL=1` or `make apply-global FORCE=1`.
GLOBAL_UNITS = $(shell $(EFFECTIVE_SCRIPT) list --global)

.PHONY: {phony_targets}

help:
	@echo \"Targets:\"
	@echo \"  make upgrade                # self-upgrade ros2-systemd-manager via pip\"
	@echo \"  make install                # install unit files only\"
	@echo \"  make apply                  # install + start + enable\"
	@echo \"  make start                  # systemctl start all configured units\"
	@echo \"  make stop                   # systemctl stop all configured units\"
	@echo \"  make restart                # systemctl restart all configured units\"
	@echo \"  make status                 # systemctl status all configured units\"
	@echo \"  make status-long            # systemctl status with 100 log lines\"
	@echo \"  make enable                 # systemctl enable all configured units\"
	@echo \"  make disable                # systemctl disable all configured units\"
	@echo \"  make logs                   # follow logs for all configured units\"
	@echo \"  make <op>-<service>         # op in start/stop/restart/status/enable/disable/logs\"
	@echo \"  make <op>-<service>-<sfx>   # e.g. status-<svc>-long, logs-<svc>-recent\"
	@echo \"  make uninstall              # uninstall all configured units\"
	@echo \"  make update                 # stop old + uninstall removed + install/start/enable + refresh generated mk\"
	@echo \"  make makefile               # refresh generated mk only (no systemd changes)\"
	@echo \"\"
	@echo \"  Flags (set on the command line):\"
	@echo \"    ALL=1      include explicit_start/explicit_stop services (per config)\"
	@echo \"    GLOBAL=1   act across every tracked config (alias for the *-global targets)\"
	@echo \"    FORCE=1    skip confirmation prompts (--force)\"
	@echo \"\"
	@echo \"  Across ALL tracked configs (every directory ever installed):\"
	@echo \"  make list                   # print this config's units (list-global: every config)\"
	@echo \"  make <op>-global            # op in start/stop/restart/status/enable/disable/logs\"
	@echo \"  make install-global         # install every tracked config\"
	@echo \"  make apply-global           # apply every tracked config\"
	@echo \"  make update-global          # update every tracked config\"
	@echo \"  make uninstall-global       # uninstall every tracked unit\"
	@echo \"  make <target> CONFIG=./file.yaml  # override auto-discovered yaml\"

ensure-config:
	@if [ -z "$(EFFECTIVE_CONFIG)" ]; then \\
		echo "ERROR: no yaml config found in current directory (expected ./ros2_services.yaml or ./*.yaml)."; \\
		exit 1; \\
	fi

upgrade:
	$(EFFECTIVE_SCRIPT) upgrade

install: ensure-config
	$(SUDO) $(EFFECTIVE_SCRIPT) install $(if $(ALL),--all,) $(if $(FORCE),--force,) --config \"$(EFFECTIVE_CONFIG)\"

apply: ensure-config
	$(SUDO) $(EFFECTIVE_SCRIPT) apply $(if $(ALL),--all,) $(if $(FORCE),--force,) --config \"$(EFFECTIVE_CONFIG)\"

uninstall: ensure-config
	$(SUDO) $(EFFECTIVE_SCRIPT) uninstall $(if $(ALL),--all,) $(if $(FORCE),--force,) --config \"$(EFFECTIVE_CONFIG)\"

start:
\t$(SUDO) systemctl start $(if $(ALL),$(UNITS),$(START_UNITS))

stop:
\t$(SUDO) systemctl stop $(if $(ALL),$(UNITS),$(STOP_UNITS))

restart:
\t$(SUDO) systemctl restart $(if $(ALL),$(UNITS),$(RESTART_UNITS))

status:
\t$(SUDO) systemctl status $(UNITS)

status-long:
	$(SUDO) systemctl status $(UNITS) --no-pager -l -n 100

enable:
\t$(SUDO) systemctl enable $(if $(ALL),$(UNITS),$(START_UNITS))

disable:
\t$(SUDO) systemctl disable $(if $(ALL),$(UNITS),$(STOP_UNITS))

logs:
	$(SUDO) journalctl $(foreach u,$(UNITS),-u $(u)) -f

logs-recent:
	$(SUDO) journalctl $(foreach u,$(UNITS),-u $(u)) -n 200 --no-pager

update: ensure-config
	$(SUDO) $(EFFECTIVE_SCRIPT) update $(if $(ALL),--all,) $(if $(FORCE),--force,) --config \"$(EFFECTIVE_CONFIG)\"

makefile: ensure-config
	$(EFFECTIVE_SCRIPT) makefile --config \"$(EFFECTIVE_CONFIG)\"

list: ensure-config
	$(EFFECTIVE_SCRIPT) list --config \"$(EFFECTIVE_CONFIG)\"

# --- across ALL tracked configs (every directory ever installed) ---
# These ignore CONFIG and act on every unit the tool has installed.

start-global:
	$(SUDO) systemctl start $(GLOBAL_UNITS)

stop-global:
	$(SUDO) systemctl stop $(GLOBAL_UNITS)

restart-global:
	$(SUDO) systemctl restart $(GLOBAL_UNITS)

status-global:
	$(SUDO) systemctl status $(GLOBAL_UNITS)

status-global-long:
	$(SUDO) systemctl status $(GLOBAL_UNITS) --no-pager -l -n 100

enable-global:
	$(SUDO) systemctl enable $(GLOBAL_UNITS)

disable-global:
	$(SUDO) systemctl disable $(GLOBAL_UNITS)

logs-global:
	$(SUDO) journalctl $(addprefix -u ,$(GLOBAL_UNITS)) -f

logs-recent-global:
	$(SUDO) journalctl $(addprefix -u ,$(GLOBAL_UNITS)) -n 200 --no-pager

install-global:
	$(SUDO) $(EFFECTIVE_SCRIPT) install --global $(if $(ALL),--all,) $(if $(FORCE),--force,)

apply-global:
	$(SUDO) $(EFFECTIVE_SCRIPT) apply --global $(if $(ALL),--all,) $(if $(FORCE),--force,)

uninstall-global:
	$(SUDO) $(EFFECTIVE_SCRIPT) uninstall --global $(if $(ALL),--all,) $(if $(FORCE),--force,)

update-global:
	$(SUDO) $(EFFECTIVE_SCRIPT) update --global $(if $(ALL),--all,) $(if $(FORCE),--force,)

list-global:
	$(EFFECTIVE_SCRIPT) list --global

{per_service_blocks_text}
"""


def write_makefile(config: Dict[str, Any], config_path: Path) -> Path:
    """Generate (or overwrite) Makefile based on YAML workspace services."""
    workspaces = config.get("workspaces", {})
    unit_names: List[str] = []
    start_units: List[str] = []
    stop_units: List[str] = []
    restart_units: List[str] = []
    for ws_cfg in workspaces.values():
        for svc in ws_cfg.get("services", []):
            name = svc["unit_name"]
            explicit_start = bool(svc.get("explicit_start", False))
            explicit_stop = bool(svc.get("explicit_stop", False))
            unit_names.append(name)
            if not explicit_start:
                start_units.append(name)
            if not explicit_stop:
                stop_units.append(name)
            if not explicit_start and not explicit_stop:
                restart_units.append(name)

    if not unit_names:
        err("No services found in any workspace; cannot build Makefile units.")
        sys.exit(1)

    output_path = resolve_makefile_path(config, config_path)
    _migrate_legacy_auto_generated_makefile(config_path.parent, output_path)
    _ensure_main_makefile_includes_fragment(
        config_path.parent, output_path.name)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    makefile_cfg = config.get("makefile", {})
    script_default_raw = str(makefile_cfg.get(
        "command", "ros2-systemd-manager")).strip()
    script_default = script_default_raw or "ros2-systemd-manager"
    content = build_makefile_content(
        script_default=script_default,
        unit_names=unit_names,
        start_units=start_units,
        stop_units=stop_units,
        restart_units=restart_units,
    )

    output_path.write_text(content, encoding="utf-8")
    log(f"Generated Makefile fragment: {output_path}")
    return output_path
